### ISSUE TITLE
VrxGrid - Edit value

### ISSUE THREAD

**Issue by Phoenonical** [sirius-ea/VireoXlibrary#26]
**Describe the bug**
I am using a 'cell-clicked' event listener to check when the user clicks on a '**Checkbox**' located in a GridRow. Upon clicking it, expect the row to update with the new checkbox value, instead, the event is launched before the row is accordingly updated. Yet when I print the row data, I receive the correctly updated row, but when I pass it to a function, the old values are passed.

**To Reproduce**
1. Create grid with the config below
2. Click on any checkbox
3. The first console.log prints the correctly updated row, but the old row data is passed into the function.

**Expected behavior**
For the row data to be updated before emitting the 'cell-clicked' event

## Additional context
My code:

### Typescript

```typescript
function clickManager(cell: {
  cellId: string | number;
  rowId: string | number;
  value: any;
}) {
  const row = gridManager.value.getRowById(cell.rowId);
  switch (cell.cellId) {
    case "enabled":
    case "highFrequency":
      console.log(row); // Prints correct data
      prop.updateAction(row.data); // Passes the old data
      break;
  }
}
```

### Vue

```vue
  <VrxGrid
    @cell-clicked="clickManager"
    class="!h-full overflow-y-auto border-b-2 border-moody-blue-800"
    :grid-configuration="configuration"
    ref="gridManager"
    :grid-data="serializedDBs"
  />
```

### Grid config

```typescript
const configuration: any = {
  id: "sourceDBs",
  selectable: false,
  multiselect: false,
  header: [
    {
      text: "enabled",
      id: "enabled",
      align: "left",
      type: "boolean",
      width: 50,
      editable: true,
    },
    {
      text: "Database Name",
      id: "databaseName",
      align: "left",
      sortable: true,
      filterType: "text",
      filterPlaceholder: "Search by Instance",
      width: 250,
    },
    {
      text: "High frequency",
      id: "highFrequency",
      align: "left",
      editable: true,
      type: "boolean",
      width: 100,
    },
  ],
};
```

**Comment by Crish15** [comment]
Per quanto riguarda la stampa con il valore corretto è dovuto al fatto che stai stampando un oggetto e non un valore. Aprendolo nella console vedrai il valore aggiornato, ma nel momento in cui lo richiami il suo valore è ancora quello precedente.
L'evento del click, in ogni caso, deve essere triggerato alla fine di tutte le operazioni di aggiornamento

**Comment by Crish15** [comment]
Now it will change the value before emitting the click event
