### ISSUE TITLE
VrxSelect - Class

### ISSUE THREAD

**Issue by Phoenonical** [sirius-ea/VireoXlibrary#30]
### Bug description
I am unable to apply custom classes

### To Reproduce
1. Use property 'class' on VrxSelect
![image](https://github.com/sirius-ea/VireoXlibrary/assets/56847260/0a5546ae-f697-4b40-8fab-b7dbf536a3ad)
2. Classes are not applied on the component
![image](https://github.com/sirius-ea/VireoXlibrary/assets/56847260/30ad9fc3-fb42-4b2a-87aa-abe38e294449)

The results are identical even with the following: 
```html
<VrxSelect
.....
class="!h-fit !col-span-2"
>
```
This behavior is **NOT** present on the other components, such as 'VrxInput'.

### Expected behavior
For the classes to be applied on the main component element.

**EDIT** 
Same behavior is present with the "id" property

**Comment by Crish15** [comment]
Added property elementClass to handle the behavior
